version: 2.1

jobs:
  build:
    resource_class: medium
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: build and push
          command: |
            chmod 555 ./gradlew
            ./gradlew clean build -x test --stacktrace
            VERSION=$(./gradlew printVersion)
            scp ./build/libs/hikkitop-${VERSION}.jar $ALI_SWAS_USER@$ALI_SWAS_HOST :/app/ 

  deploy:
    docker:
      - image: cimg/base
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $ALI_SWAS_USER@$ALI_SWAS_HOST 
            "cd /app/hikkitop \n
            git pull \n
            sleep 5s \n
            sh /app/hikkitop/scripts/deployer.sh"

workflows:
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main