version: 2.1

executors:
  docker-container-builder:
    docker:
      - image: docker:19.03.9-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN

jobs:
  build-jar:
    resource_class: medium+
    docker:
      - image: cimg/openjdk:20.0
    steps:
      - checkout
      - run:
          name: build jar
          command: |
            chmod 555 ./gradlew
            ./gradlew clean build -x test -x jsBrowserTest --stacktrace
            VERSION=$(./gradlew printVersion |  cut -d " " -f 6 | sed 's/ //g')
            echo ${VERSION} > /tmp/version.txt
            mkdir -p /tmp/libs
            SOURCE=$(echo "./build/libs/hikkitop-"${VERSION}".jar" | sed 's/ //g')
            cp ${SOURCE} /tmp/libs/hikkitop.jar
            cp ./src/jvmMain/resources/AudioReverser.py /tmp/AudioReverser.py
      - persist_to_workspace:
          root: /tmp
          paths:
            - version.txt
            - AudioReverser.py
            - libs/hikkitop.jar

  build-and-push-image:
    resource_class: small
    executor: docker-container-builder
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp
      - run:
          name: docker build
          command: |
            VERSION="$(cat /tmp/version.txt)"
            DOCKER_BUILDKIT=1 docker build --build-arg VERSION="$VERSION" --tag hikkitop:latest -f ./Dockerfile /tmp
      - run:
          name: push image to docker hub
          command: |
            VERSION="$(cat /tmp/version.txt)"
            if [ "${CIRCLE_BRANCH}" = "dev" ]; then
              VERSION=dev
            fi
            docker tag hikkitop:latest hypingdog/hikkitop:"$VERSION"
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
            docker push hypingdog/hikkitop:"$VERSION"

workflows:
  build-and-deploy:
    jobs:
      - build-jar
      - build-and-push-image:
          requires:
            - build-jar